### PR TITLE
Cookie authentication changes

### PR DESCRIPTION
**Pull request by victorg1991**
Hi guys!

I'm here again with another PR 🎉

This is change is similar to iOS one, we need username and password in the cookieAuthentication class. In this one we have added a sync method to get the cookie auth because it fits better with our current architecture.

Any comments would be appreciated

Thanks! :)

### CODE REVIEW

**Comment by victorg1991** [comment]
I'm going to send a new PR tomorrow with some iOS changes for swift3 annotations (nullable nonnull etc)

**Comment by victorg1991** [comment]
This is the last pull we need to be merged for our next Liferay Screens release :)
@brunofarache @sgosantos 

Thanks!

**Comment by sgosantos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sgosantos** [comment]
I've reviewed the code, but it seems I don't have permission to push the changes. @brunofarache, can you give it to me?

**Comment by sgosantos** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-mobile-sdk/compare/46843f5~4...46843f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
