### PR TITLE
Add Liferay Go SDK by @Ithildir

### PR DESCRIPTION
**Pull request by zenorocha**

### CODE REVIEW

**Comment by brunofarache** [comment]
we will include mobile related SDKs only.

**Comment by yuchi** [comment]
Actually Go can be used to [build android apps](http://blog.golang.org/go1.4) and Liferay Connector is both for Node.js and Titanium SDK… so…

**Comment by yuchi** [comment]
And the Windows Mobile SDK is a PCL, AFAIK it works perfectly for Xbox development…

**Comment by brunofarache** [comment]
You can only use Go through the NDK, I think, let's wait for the day we can develop full Android apps with Go only :).

Zeno is planning to add all these non-mobile platforms clients to https://dev.liferay.com

**Pull request closed without merging**
