### PR TITLE
Objective-C - Swift interoperability annotations

### PR DESCRIPTION
**Pull request by victorg1991**
This PR add some annotations to swift code in order to improve the interoperability with Swift.

Basically this annotations have information about the nullability of the different return types and 
parameters.

One extra thing, Xcode converts  methods with a NSError** parameter into a throws function in swift but if the return type is void it doesn't do the conversion. To force Xcode to do the conversion we need to use the macro added in `Macros.h` CONVERT_ERROR_TO_THROWS. I have changed the template for generating the services to add this macro when the method returns void.

Any comments or questions will be appreciated :)

### CODE REVIEW

**Comment by victorlaerte** [comment]
@victorg1991 Can you fix the conflicts ?

**Comment by victorg1991** [comment]
Done :D (Remember that this PR has breaking changes)

**Comment by victorg1991** [comment]
This now depends on https://github.com/liferay/liferay-mobile-sdk/pull/52

**Comment by allanragec** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by allanragec** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by allanragec** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by allanragec** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
